# Generated by Django 5.1.4 on 2025-05-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('maps', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/cards/%Y/%m/%d/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Изображение карточки',
                'verbose_name_plural': 'Изображения карточки',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='cards', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Страна')),
                ('description', models.TextField(verbose_name='Описание страны')),
                ('cards', models.ManyToManyField(blank=True, related_name='counties', to='catalog.card', verbose_name='Карточки')),
            ],
        ),
    ]
