# Generated by Django 5.1.4 on 2025-04-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_image1_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='catergory',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='card_categorys', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='card',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='card_images', to='catalog.image', verbose_name='Изображения'),
        ),
    ]
