# Generated by Django 5.1.4 on 2025-05-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_card_catergory_remove_card_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='images',
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='cards', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/cards/%Y/%m/%d/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Изображение карточки',
                'verbose_name_plural': 'Изображения карточки',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
