# Generated by Django 5.1.4 on 2025-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_card_images_alter_card_category_cardimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Страны')),
                ('description', models.TextField(verbose_name='Описание страны ')),
                ('card', models.ManyToManyField(blank=True, related_name='Card', to='catalog.card', verbose_name='Карточки')),
            ],
        ),
    ]
