# Generated by Django 5.1.4 on 2025-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='card',
        ),
        migrations.AddField(
            model_name='county',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='counties', to='catalog.card', verbose_name='Карточки'),
        ),
        migrations.AlterField(
            model_name='county',
            name='description',
            field=models.TextField(verbose_name='Описание страны'),
        ),
        migrations.AlterField(
            model_name='county',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
    ]
